##
# A reusable workflow that runs the performance test suite.
##
name: Run performance Tests

on:
  workflow_call:
    inputs:
      LOCAL_DIR:
        description: 'Where to run WordPress from.'
        required: false
        type: 'string'
        default: 'build'
      BASE_TAG:
        description: 'The version being used for baseline measurements.'
        required: false
        type: 'string'
        default: '6.7.0'
      php-version:
        description: 'The PHP version to use.'
        required: false
        type: 'string'
        default: 'latest'
      memcached:
        description: 'Whether to enable memcached.'
        required: false
        type: 'boolean'
        default: false
      multisite:
        description: 'Whether to use Multisite.'
        required: false
        type: 'boolean'
        default: false
    secrets:
      CODEVITALS_PROJECT_TOKEN:
        description: 'The authorization token for https://www.codevitals.run/project/wordpress.'
        required: false

env:
  PUPPETEER_SKIP_DOWNLOAD: ${{ true }}
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ true }}
  # Performance testing should be performed in an environment reflecting a standard production environment.
  LOCAL_WP_DEBUG: false
  LOCAL_SCRIPT_DEBUG: false
  LOCAL_SAVEQUERIES: false
  LOCAL_WP_DEVELOPMENT_MODE: "''"

  # This workflow takes two sets of measurements — one for the current commit,
  # and another against a consistent version that is used as a baseline measurement.
  # This is done to isolate variance in measurements caused by the GitHub runners
  # from differences caused by code changes between commits. The BASE_TAG value here
  # represents the version being used for baseline measurements. It should only be
  # changed if we want to normalize results against a different baseline.
  BASE_TAG: ${{ inputs.BASE_TAG }}
  LOCAL_DIR: ${{ inputs.LOCAL_DIR }}
  TARGET_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || '' }}
  TARGET_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

  LOCAL_PHP_MEMCACHED: ${{ inputs.memcached }}
  LOCAL_PHP: ${{ inputs.php-version }}${{ 'latest' != inputs.php-version && '-fpm' || '' }}
  LOCAL_MULTISITE: ${{ inputs.multisite }}

jobs:
  performance:
    name: ${{ inputs.multisite && 'Multisite' || 'Single site' }} / ${{ inputs.memcached && 'Memcached' || 'Default' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ ! contains( github.event.before, '00000000' ) }}

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          fetch-depth: ${{ github.event_name == 'workflow_dispatch' && '2' || '1' }}

      # The `workflow_dispatch` event is the only one missing the needed SHA to target.
      - name: Retrieve previous commit SHA (if necessary)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "TARGET_SHA=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run performance tests (current commit)
        run: npm run test:performance
